apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-workload
  namespace: demo-cluster
  labels:
    app: cluster-workload
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cluster-workload
  template:
    metadata:
      labels:
        app: cluster-workload
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
