apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: file-writer
  namespace: pvc-demo
spec:
  serviceName: file-writer
  replicas: 1
  selector:
    matchLabels:
      app: file-writer
  template:
    metadata:
      labels:
        app: file-writer
      annotations:
        backup.velero.io/backup-volumes: data
    spec:
      containers:
      - name: writer
        image: busybox
        command:
        - sh
        - -c
        - |
          if [ ! -f /data/hello.txt ]; then
            echo "hello from pvc" > /data/hello.txt
          fi
          sleep 3600
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
